/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: usp-record.proto */

#ifndef PROTOBUF_C_usp_2drecord_2eproto__INCLUDED
#define PROTOBUF_C_usp_2drecord_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _UspRecord__Record UspRecord__Record;
typedef struct _UspRecord__NoSessionContextRecord UspRecord__NoSessionContextRecord;
typedef struct _UspRecord__SessionContextRecord UspRecord__SessionContextRecord;


/* --- enums --- */

typedef enum _UspRecord__Record__PayloadSecurity {
  USP_RECORD__RECORD__PAYLOAD_SECURITY__PLAINTEXT = 0,
  USP_RECORD__RECORD__PAYLOAD_SECURITY__TLS = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(USP_RECORD__RECORD__PAYLOAD_SECURITY)
} UspRecord__Record__PayloadSecurity;
typedef enum _UspRecord__SessionContextRecord__PayloadSARState {
  /*
   *No segmentation
   */
  USP_RECORD__SESSION_CONTEXT_RECORD__PAYLOAD_SARSTATE__NONE = 0,
  /*
   *Begin segmentation
   */
  USP_RECORD__SESSION_CONTEXT_RECORD__PAYLOAD_SARSTATE__BEGIN = 1,
  /*
   *Segmentation in process
   */
  USP_RECORD__SESSION_CONTEXT_RECORD__PAYLOAD_SARSTATE__INPROCESS = 2,
  /*
   *Segmentation is complete
   */
  USP_RECORD__SESSION_CONTEXT_RECORD__PAYLOAD_SARSTATE__COMPLETE = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(USP_RECORD__SESSION_CONTEXT_RECORD__PAYLOAD_SARSTATE)
} UspRecord__SessionContextRecord__PayloadSARState;

/* --- messages --- */

typedef enum {
  USP_RECORD__RECORD__RECORD_TYPE__NOT_SET = 0,
  USP_RECORD__RECORD__RECORD_TYPE_NO_SESSION_CONTEXT = 7,
  USP_RECORD__RECORD__RECORD_TYPE_SESSION_CONTEXT = 8
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(USP_RECORD__RECORD__RECORD_TYPE)
} UspRecord__Record__RecordTypeCase;

struct  _UspRecord__Record
{
  ProtobufCMessage base;
  char *version;
  char *to_id;
  char *from_id;
  UspRecord__Record__PayloadSecurity payload_security;
  /*
   *MAC or Signature
   */
  ProtobufCBinaryData mac_signature;
  ProtobufCBinaryData sender_cert;
  UspRecord__Record__RecordTypeCase record_type_case;
  union {
    UspRecord__NoSessionContextRecord *no_session_context;
    UspRecord__SessionContextRecord *session_context;
  };
};
#define USP_RECORD__RECORD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&usp_record__record__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, USP_RECORD__RECORD__PAYLOAD_SECURITY__PLAINTEXT, {0,NULL}, {0,NULL}, USP_RECORD__RECORD__RECORD_TYPE__NOT_SET, {0} }


struct  _UspRecord__NoSessionContextRecord
{
  ProtobufCMessage base;
  ProtobufCBinaryData payload;
};
#define USP_RECORD__NO_SESSION_CONTEXT_RECORD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&usp_record__no_session_context_record__descriptor) \
    , {0,NULL} }


struct  _UspRecord__SessionContextRecord
{
  ProtobufCMessage base;
  uint64_t session_id;
  uint64_t sequence_id;
  uint64_t expected_id;
  uint64_t retransmit_id;
  UspRecord__SessionContextRecord__PayloadSARState payload_sar_state;
  UspRecord__SessionContextRecord__PayloadSARState payloadrec_sar_state;
  size_t n_payload;
  ProtobufCBinaryData *payload;
};
#define USP_RECORD__SESSION_CONTEXT_RECORD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&usp_record__session_context_record__descriptor) \
    , 0, 0, 0, 0, USP_RECORD__SESSION_CONTEXT_RECORD__PAYLOAD_SARSTATE__NONE, USP_RECORD__SESSION_CONTEXT_RECORD__PAYLOAD_SARSTATE__NONE, 0,NULL }


/* UspRecord__Record methods */
void   usp_record__record__init
                     (UspRecord__Record         *message);
size_t usp_record__record__get_packed_size
                     (const UspRecord__Record   *message);
size_t usp_record__record__pack
                     (const UspRecord__Record   *message,
                      uint8_t             *out);
size_t usp_record__record__pack_to_buffer
                     (const UspRecord__Record   *message,
                      ProtobufCBuffer     *buffer);
UspRecord__Record *
       usp_record__record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   usp_record__record__free_unpacked
                     (UspRecord__Record *message,
                      ProtobufCAllocator *allocator);
/* UspRecord__NoSessionContextRecord methods */
void   usp_record__no_session_context_record__init
                     (UspRecord__NoSessionContextRecord         *message);
size_t usp_record__no_session_context_record__get_packed_size
                     (const UspRecord__NoSessionContextRecord   *message);
size_t usp_record__no_session_context_record__pack
                     (const UspRecord__NoSessionContextRecord   *message,
                      uint8_t             *out);
size_t usp_record__no_session_context_record__pack_to_buffer
                     (const UspRecord__NoSessionContextRecord   *message,
                      ProtobufCBuffer     *buffer);
UspRecord__NoSessionContextRecord *
       usp_record__no_session_context_record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   usp_record__no_session_context_record__free_unpacked
                     (UspRecord__NoSessionContextRecord *message,
                      ProtobufCAllocator *allocator);
/* UspRecord__SessionContextRecord methods */
void   usp_record__session_context_record__init
                     (UspRecord__SessionContextRecord         *message);
size_t usp_record__session_context_record__get_packed_size
                     (const UspRecord__SessionContextRecord   *message);
size_t usp_record__session_context_record__pack
                     (const UspRecord__SessionContextRecord   *message,
                      uint8_t             *out);
size_t usp_record__session_context_record__pack_to_buffer
                     (const UspRecord__SessionContextRecord   *message,
                      ProtobufCBuffer     *buffer);
UspRecord__SessionContextRecord *
       usp_record__session_context_record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   usp_record__session_context_record__free_unpacked
                     (UspRecord__SessionContextRecord *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*UspRecord__Record_Closure)
                 (const UspRecord__Record *message,
                  void *closure_data);
typedef void (*UspRecord__NoSessionContextRecord_Closure)
                 (const UspRecord__NoSessionContextRecord *message,
                  void *closure_data);
typedef void (*UspRecord__SessionContextRecord_Closure)
                 (const UspRecord__SessionContextRecord *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor usp_record__record__descriptor;
extern const ProtobufCEnumDescriptor    usp_record__record__payload_security__descriptor;
extern const ProtobufCMessageDescriptor usp_record__no_session_context_record__descriptor;
extern const ProtobufCMessageDescriptor usp_record__session_context_record__descriptor;
extern const ProtobufCEnumDescriptor    usp_record__session_context_record__payload_sarstate__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_usp_2drecord_2eproto__INCLUDED */
